openapi: 3.1.0
info:
  version: 1.0.0
  title: Watertracking app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This app is able to measure and track the amount of water you drink per day and compare it with your daily requirement.
tags:
  - name: Auth
    description: Auth operations.
  - name: Watertracking
    description: Operations related to water tracking.
  - name: Users
    description: Operations for retrieving user data by ID.
  - name: Count
    description: Operations to count all users.
servers:
  - url: https://crystal-coders-back.onrender.com
  - url: http://127.0.0.1:3000

paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  /auth/request-reset-email:
    post:
      $ref: '../swagger/paths/auth/request-reset-email.yaml'
  /auth/reset-password:
    post:
      $ref: '../swagger/paths/auth/reset-password.yaml'
  /users/{userId}:
    get:
      $ref: '../swagger/paths/users/{userId}/get.yaml'
    patch:
      $ref: '../swagger/paths/users/{userId}/patch.yaml'
    delete:
      $ref: '../swagger/paths/users/{userId}/delete.yaml'
  /count:
    get:
      $ref: '../swagger/paths/count/get.yaml'
  /water:
    get:
      $ref: '../swagger/paths/water/get.yaml'
    post:
      $ref: '../swagger/paths/water/post.yaml'
  /water/{volumeId}:
    get:
      $ref: '../swagger/paths/water/{volumeId}/get.yaml'
    patch:
      $ref: '../swagger/paths/water/{volumeId}/patch.yaml'
    delete:
      $ref: '../swagger/paths/water/{volumeId}/delete.yaml'
  /water/month:
    get:
      $ref: '../swagger/paths/water/month/get.yaml'
  /water/day:
    get:
      $ref: '../swagger/paths/water/day/get.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
