openapi: 3.1.0
info:
  version: 1.0.0
  title: Watertracking app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This app is able to measure and track the amount of water you drink per day and compare it with your daily requirement.
tags:
  - name: Auth
    description: Auth operations.
  - name: Watertracking
    description: Operations related to water tracking.
  - name: Users
    description: Operations for retrieving user data by ID.
servers:
  - url: http://localhost:3000
  - url: https://crystal-coders-back.onrender.com
paths:
  /register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  /login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /refresh:
    post:
      $ref: '../swagger/paths/auth/refresh.yaml'
  /logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  /request-reset-email:
    post:
      $ref: '../swagger/paths/auth/request-reset-email.yaml'
  /reset-password:
    post:
      $ref: '../swagger/paths/auth/reset-password.yaml'
  /users/{userId}:
    get:
      $ref: '../swagger/paths/users/{userId}/get.yaml'
    patch:
      $ref: '../swagger/paths/users/{userId}/patch.yaml'
  /users/count:
    get:
      $ref: '../swagger/paths/users/get.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
